# Generated by Django 2.2.1 on 2019-08-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=20, verbose_name='用户名')),
            ],
        ),
    ]
