# Generated by Django 2.2.4 on 2019-10-15 10:53

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.FileField(upload_to='allphotos/', verbose_name='当前图片')),
            ],
            options={
                'verbose_name': '图片保存表',
                'db_table': 'addphoto_table',
            },
        ),
        migrations.CreateModel(
            name='AdInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adphoto', models.FileField(default='/ad/1.png', upload_to='ad/', verbose_name='广告图片')),
            ],
            options={
                'verbose_name': '广告数据表',
                'db_table': 'ad_table',
            },
        ),
        migrations.CreateModel(
            name='HouseInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_images', models.FileField(default='/house/1.png', upload_to='house/', verbose_name='房屋图片')),
                ('house_title', models.CharField(default='', max_length=100, verbose_name='租房标题')),
                ('basic_interviews', models.TextField(default='', verbose_name='文字介绍')),
                ('house_price', models.IntegerField(default=0, verbose_name='房屋价格')),
                ('house_position', models.TextField(default='', verbose_name='房屋地址')),
                ('connect_phone', models.CharField(default='', max_length=20, verbose_name='联系手机号')),
                ('renter_name', models.TextField(default='', verbose_name='业主姓名')),
            ],
            options={
                'verbose_name': '房屋信息表',
                'db_table': 'houseinfo_table',
            },
        ),
        migrations.CreateModel(
            name='LandlordManage',
            fields=[
                ('tenant', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='租户姓名')),
                ('rental_time', models.DateField(verbose_name='出租时间')),
                ('rental_address', models.CharField(default='', max_length=100, verbose_name='出租地址')),
                ('rent_fee', models.IntegerField(verbose_name='房租')),
                ('water_fee', models.IntegerField(verbose_name='水费')),
                ('electric_fee', models.IntegerField(verbose_name='电费')),
                ('is_net', models.BooleanField(default=True, verbose_name='是否有网费')),
                ('net_fee', models.IntegerField(verbose_name='网费')),
                ('key_num', models.IntegerField(verbose_name='钥匙数量')),
                ('is_air', models.BooleanField(default=True, verbose_name='是否有空调')),
                ('is_washer', models.BooleanField(default=True, verbose_name='是否有洗衣机')),
            ],
            options={
                'verbose_name': '房东记录表',
                'db_table': 'landlord_table',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=100, verbose_name='密码')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('phone_number', models.CharField(default='', max_length=11, unique=True, verbose_name='手机号')),
                ('rent_address', models.CharField(default='', max_length=30, verbose_name='住址')),
                ('idcard', models.CharField(default='', max_length=20, unique=True, verbose_name='身份证')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息表',
                'db_table': 'user_table',
                'ordering': ['-username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
