# Generated by Django 2.2.4 on 2019-09-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_images', models.ImageField(default='', upload_to='house/', verbose_name='房屋图片')),
                ('basic_interviews', models.TextField(default='', verbose_name='文字介绍')),
                ('house_price', models.IntegerField(default=0, verbose_name='房屋价格')),
                ('house_position', models.TextField(default='', verbose_name='房屋地址')),
                ('connect_phone', models.CharField(default='', max_length=20, verbose_name='联系手机号')),
                ('renter_name', models.TextField(default='', verbose_name='业主姓名')),
            ],
            options={
                'verbose_name': '房屋信息表',
                'db_table': 'houseinfo_table',
            },
        ),
    ]
