# Generated by Django 2.2.4 on 2019-09-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_houseinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfomodel',
            name='house_images',
            field=models.FileField(default='/house/1.png', upload_to='house/', verbose_name='房屋图片'),
        ),
    ]
