# Generated by Django 2.2.4 on 2019-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190904_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.FileField(upload_to='house/', verbose_name='当前图片')),
            ],
        ),
    ]
