# Generated by Django 2.2.4 on 2019-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_addphotomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addphotomodel',
            name='photos',
            field=models.FileField(upload_to='allphotos/', verbose_name='当前图片'),
        ),
    ]
