# Generated by Django 2.2.1 on 2019-08-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190825_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': '用户信息表'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
