# Generated by Django 2.2.1 on 2019-08-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190825_2138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user_table',
        ),
    ]
