# Generated by Django 2.2.4 on 2019-09-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190904_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addphotomodel',
            options={'verbose_name': '图片保存表'},
        ),
        migrations.AlterModelTable(
            name='addphotomodel',
            table='addphoto_table',
        ),
    ]
