# Generated by Django 2.2.4 on 2019-08-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190825_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='', max_length=120, verbose_name='密码'),
        ),
    ]
