# Generated by Django 2.2.4 on 2019-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190904_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfomodel',
            name='house_title',
            field=models.CharField(default='', max_length=100, verbose_name='租房标题'),
        ),
    ]
