# Generated by Django 2.2.4 on 2019-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_houseinfomodel_house_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordManage',
            fields=[
                ('tenant', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='租户姓名')),
                ('rental_time', models.DateField(verbose_name='出租时间')),
                ('rental_address', models.CharField(default='', max_length=100, verbose_name='出租地址')),
                ('rent_fee', models.IntegerField(verbose_name='房租')),
                ('water_fee', models.IntegerField(verbose_name='水费')),
                ('electric_fee', models.IntegerField(verbose_name='电费')),
                ('is_net', models.BooleanField(default=True, verbose_name='是否有网费')),
                ('net_fee', models.IntegerField(verbose_name='网费')),
                ('key_num', models.IntegerField(verbose_name='钥匙数量')),
                ('is_air', models.BooleanField(default=True, verbose_name='是否有空调')),
                ('is_washer', models.BooleanField(default=True, verbose_name='是否有洗衣机')),
            ],
            options={
                'verbose_name': '房东记录表',
                'db_table': 'landlord_table',
            },
        ),
    ]
