# Generated by Django 2.2.4 on 2019-08-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190826_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='密码'),
        ),
    ]
