# Generated by Django 2.2.4 on 2019-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190826_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='idcard',
            field=models.CharField(default='', max_length=20, verbose_name='身份证'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rent_address',
            field=models.CharField(default='', max_length=30, verbose_name='住址'),
        ),
    ]
