# Generated by Django 2.2.1 on 2019-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_landlordmanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adphoto', models.FileField(default='/house/1.png', upload_to='ad/', verbose_name='广告图片')),
            ],
            options={
                'verbose_name': '广告数据表',
                'db_table': 'ad_table',
            },
        ),
    ]
