# Generated by Django 2.2.4 on 2019-08-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190826_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='idcard',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
