# Generated by Django 2.2.4 on 2019-09-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190827_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='YYModel',
            fields=[
                ('username', models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
            ],
        ),
    ]
