# Generated by Django 2.2.4 on 2019-09-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190924_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adinfomodel',
            name='adphoto',
            field=models.FileField(default='/ad/1.png', upload_to='ad/', verbose_name='广告图片'),
        ),
    ]
