# Generated by Django 2.2.4 on 2019-09-03 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_yymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YYModel',
        ),
    ]
